### ISSUE TITLE
how to run multiple builds with spin.js?

### ISSUE THREAD

**Issue by veeramarni** [sysgears/spinjs#13] opened 2017-10-17 03:57 UTC
Based on the code [here](https://github.com/sysgears/spin.js/blob/master/src/requireModule.ts#L4)  `spinjs` look for local node modules from where it runs. 

But with`lerna` type of setup, we can have all `node_modules` installed in the `root`. And all sub folder packages can use them (which lerna handles it transparently). And we may need to include the `module` in `package.json`that brings in binaries. More details are [here](https://github.com/lerna/lerna/blob/master/doc/hoist.md#module-resolution)

But in this case, I need to manually symbolic link the `node_modules` as the `requireModule` is resolving to only local `node_modules` directory. 

For more clarity, following are two `.spinrc.json` files, each configured for a different build. But due to above issue, i cannot build it from `servers/frontend-server` as it fails with following error. 
https://github.com/cdmbase/fullstack-pro/blob/spinjs/.spinrc.json
https://github.com/cdmbase/fullstack-pro/blob/spinjs/servers/frontend-server/.spinrc.json

error
---
```

spin error { Error: Cannot find module '/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/servers/frontend-server/node_modules/webpack'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.requireModule [as default] (/Users/veeramar

```

**Comment by vlasenko** [comment] 2017-10-17 05:14
@veeramarni Yes, I was going to have lerna hoisted modules support a bit later, but I will investigate now, whether it is possible to add it quickly

**Comment by vlasenko** [comment] 2017-10-17 14:18
@veeramarni Just FYI, I'm working on this issue. Currently `spin.js` itself doesn't have issues with utilizing hoisted packages, however all the tools that `spin.js` relies on should support this or we need to invent workarounds. One of the dependencies we rely on is `webpack-node-externals`. It is not hoisted packages friendly. I'm working on a workaround at the moment.

**Comment by vlasenko** [comment] 2017-10-17 14:34
@veeramarni I have published `spinjs@0.4.15` which should have initial support for hoisted packages. Though I think it will require much more efforts. But initial support is pushed into 0.4.15

**Comment by veeramarni** [comment] 2017-10-17 15:22
Thanks, just tested it. Looks like `webpack` has parse problems with some of the `node_modules`, this could be due to removing `webpack-node-externals` as we don't need to create `dll` for some of the node modules. 

I usually do builds like below in `lerna` build. That way webpack don't try to build `node_modules` that related to `server`. 
```
 externals: [nodeExternals({ modulesDir: "../../node_modules" }),
  ]
```

Error
---
```
ERROR in ./node_modules/npm/bin/npm-cli.js
Module parse failed: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/node_modules/npm/bin/npm-cli.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| ;(function () { // wrapper in case we're in module_context mode
|   // windows: running "npm blah" in this folder will invoke WSH, not node.
 @ ./node_modules/npm/lib/npm.js 401:4-32
 @ ./node_modules/node-pre-gyp/lib/util/compile.js
 @ ./node_modules/node-pre-gyp/lib ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ dll vendor

ERROR in ./node_modules/rc/index.js
Module parse failed: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/node_modules/rc/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| var cc   = require('./lib/utils')
| var join = require('path').join
 @ ./node_modules/node-pre-gyp/lib/unpublish.js 12:13-26
 @ ./node_modules/node-pre-gyp/lib ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ dll vendor
```

**Comment by vlasenko** [comment] 2017-10-17 16:51
@veeramarni Could you point me to source code where I can reproduce this?

**Comment by vlasenko** [comment] 2017-10-17 17:07
@veeramarni node-externals should be used for server code only and for server code dll shouldn't be generated at all. From the details you have posted it is not clear for which platform the dll is generated for web front-end or for the server code?

**Comment by veeramarni** [comment] 2017-10-17 18:47
I agree, but right now `dll` are been build for server side `node_modules` as  well and causing `webpack` parse issues. 

As shown in the following log. 

[watch.log](https://github.com/sysgears/spin.js/files/1392195/watch.log)

**Comment by vlasenko** [comment] 2017-10-18 03:37
@veeramarni There is clearly a problem with your package dependencies. In your logs it is seen that your package for web is dependent on `node-pre-gyp` and other server-side packages. Please fix your package dependencies

**Comment by veeramarni** [comment] 2017-10-18 20:54
@vlasenko 

I don't see we are referring any of server packages as dependency in `web` package. What I have noticed, that `dll` is picking all the `dependencies` section of the `package.json` to build it. 

I have following modules in `dependencies` section and `dll` is picking all of them. 

```
  "dependencies": {
    "@cdm-logger/client": "^3.1.0",
    "@cdm-logger/server": "^3.0.2",
    "apollo-client": "^1.9.2",
    "apollo-link": "^0.7.0",
    "apollo-logger": "^0.1.0",
    "body-parser": "^1.18.2",
    "browser-bunyan": "^0.4.0",
    "bunyan": "^1.8.10",
    "classnames": "^2.2.5",
    "cors": "^2.8.3",
    "export-dir": "^0.1.2",
    "express": "^4.16.2",
    "fela": "^5.2.0",
    "fela-beautifier": "^5.0.7",
    "fela-font-renderer": "^5.0.8",
    "fela-perf": "^5.0.2",
    "fela-plugin-fallback-value": "^5.0.8",
    "fela-plugin-logger": "^5.0.3",
    "fela-plugin-lvha": "^5.0.7",
    "fela-plugin-prefixer": "^5.0.8",
    "fela-plugin-unit": "^5.0.7",
    "fela-plugin-validator": "^5.0.7",
    "graphql": "^0.10.5",
    "graphql-nats-subscriptions": "^1.0.8",
    "graphql-server-core": "^1.1.0",
    "graphql-server-express": "^1.1.2",
    "graphql-subscriptions": "^0.5.0",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "1.2.2",
    "helmet": "^3.6.0",
    "hemera-joi": "^1.2.2",
    "hemera-plugin": "0.0.12",
    "hemera-testsuite": "^1.3.0",
    "immutability-helper": "^2.2.2",
    "inversify": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "knex": "^0.13.0",
    "morgan": "^1.8.1",
    "nats": "^0.7.20",
    "nats-hemera": "^1.5.13",
    "nconf": "^0.8.4",
    "node-pre-gyp": "~0.6.31",
    "persistgraphql": "^0.3.10",
    "prop-types": "^15.5.8",
    "ramda": "^0.25.0",
    "react": "^15.5.4",
    "react-apollo": "^1.4.15",
    "react-dom": "^15.5.4",
    "react-fela": "^5.3.0",
    "react-helmet": "^5.2.0",
    "react-redux": "^5.0.5",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^4.0.8",
    "reactstrap": "^4.6.2",
    "recompose": "^0.25.0",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.2",
    "redux-injectable-reducer": "^1.0.3",
    "redux-injectable-store": "^1.0.0",
    "redux-loop": "^3.2.0",
    "redux-thunk": "^2.2.0",
    "reflect-metadata": "^0.1.10",
    "reselect": "^3.0.0",
    "rxjs": "^5.4.3",
    "sequelize": "^4.8.4",
    "serialize-javascript": "^1.4.0",
    "sqlite3": "^3.1.8",
    "styled-components": "^2.0.0",
    "subscriptions-transport-ws": "^0.8.3"
  }
```

**Comment by veeramarni** [comment] 2017-10-18 21:00
I think i need to add the `dependencies` types categorized as `web`, `server` that should fix this issue. I will give that the try.

**Comment by veeramarni** [comment] 2017-10-18 21:03
Going back to your previous comment

> @veeramarni I have published spinjs@0.4.15 which should have initial support for hoisted packages. Though I think it is quite possible that the support might require much more efforts. I will be happy though if 0.4.15 work without issues :)

What else is still pending and needs efforts? If you can give me a rough idea, we want to see how we can contribute it.

**Comment by vlasenko** [comment] 2017-10-19 04:42
@veeramarni Yes, `spin.js` tries to build a dll from all modules listed in `package.json -> dependencies`. If you run multiple builders on the same `package.json` you need to specify in `dependencyPlatforms` which dependency belongs to which builder, so that `spin.js` didn't try to put `server` dependencies into a `web` `dll`.

I don't know what is still pending to support hoisted packages, I hope that nothing. We need to test `spin.js` in various scenarios with hosted packages and then find out problems and fix them

**Comment by vlasenko** [comment] 2017-10-19 05:14
@veeramarni However there are many other areas to contribute. For example make current plugins more flexible by making them work even when some optional dependencies are not installed, like was the case with `postcss-loader`, or provide default configuration for `postcss-loader` when it is installed, but config is missing. Write more plugins for different frameworks and libraries, help with documenting everything, etc.

**Comment by vlasenko** [comment] 2017-10-19 09:16
@veeramarni One of the features that would be nice to have is an auto-detection whether dependency is safe to put into a dll for a given platform

**Comment by veeramarni** [comment] 2017-10-19 12:54
Ok, I do see a problem with `postcss-loader` and `css-loader` as I was testing with `xterm` library which brings in `css`. Will take a look.

```
webpack-for-webDll error Error: ENOENT: no such file or directory, open './node_modules/css-loader/index.js?{"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true}!./node_modules/xterm/lib/addons/fullscreen/fullscreen.css'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Compiler.<anonymous> (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/node_modules/spinjs/src/executor.ts:610:28)
```

**Comment by vlasenko** [comment] 2017-10-19 12:58
@veeramarni  Why `.css` from inside `node_modules` is loaded at all? How it can be required inside `xterm` and why?

**Comment by veeramarni** [comment] 2017-10-19 14:03
Xterm is just in dependencies and not even imported in the code. But dll build itself is loading and failing. I m not sure it is xterm library issue or spinjs. But I did not see this issue before.

**Comment by vlasenko** [comment] 2017-10-19 14:08
`spinjs` puts into dll all the package.json dependencies. It cannot know whether the dependency is used in the code or not. It assumes everything is used. But you can exclude some dependencies from the given dll by specifying target builder in dependencyPlatforms

**Comment by vlasenko** [comment] 2017-10-19 14:09
@veeramarni If you don't want using dll set `"webpackDll": false` in `.spinrc.json -> options`

**Comment by veeramarni** [comment] 2017-10-19 14:25
No im just testing whether such kind of libraries works out with spinjs. My expectation was the dll build should be successful with that library as well. 

I would like to dig deep into it shortly.

**Comment by vlasenko** [comment] 2017-10-19 14:54
@veeramarni Yes, I can reproduce this problem, let me look too

**Comment by vlasenko** [comment] 2017-10-19 15:29
@veeramarni I think this is a problem in `xterm`. It is generally considered a bad practice to use dynamic requires inside libraries, like done here:
https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L766

See the relevant discussion in Webpack issues:
https://github.com/webpack/webpack/issues/733#issuecomment-71920930

To workaround this issue you can exclude this library from `dll` by editing `platformDependencies`.

**Comment by vlasenko** [comment] 2017-11-03 06:45
Closing this issue, because original problem was solved

**Closed by vlasenko** 2017-11-03 06:45 UTC
